using System;
using System.IO;
using System.Net;
using System.Text;
using System.Drawing;
using System.Threading;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web.Script.Serialization;

public sealed class GiftTask {
 public string id,eventKey,stream,status,lease,error,expectedId,sourceUrl,identityMethod,templateId,templateName,videoHash,playToken;
 public Dictionary<string,object> raw,profile,renderMeta;
 public long created,updated,deadline; public int attempts,slot=-1; public bool corrected;
}
public sealed class QueueSnapshot {
 public long generation,total,completed,failures,warnings,overflow;public bool enabled;public string stream;
 public List<GiftTask> tasks=new List<GiftTask>();public List<string> seen=new List<string>();
 public List<string> notices=new List<string>();
}
internal sealed class QueueStore {
 internal static readonly string DirectoryRoot=Path.Combine(UpdateManager.DataRoot,"automation-v8");
 readonly object gate=new object(); readonly string root; QueueSnapshot data;string persistenceError="";
 long edgePing,rendererPing,manualDeadline;int edgeBacklog;bool listenerEnabled,listenerCompatible;string lastNotice="";long lastNoticeAt; string edgeState="未连接 Edge 礼物页面",rendererOwner="";
 internal const int Slots=12,MaxPending=500; internal const long VideoLimit=128L*1024*1024;
 static JavaScriptSerializer Json(){return new JavaScriptSerializer{MaxJsonLength=64*1024*1024,RecursionLimit=64};}
 internal static long Now(){return DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();}
 internal static string S(Dictionary<string,object> d,string k){object v;return d!=null&&d.TryGetValue(k,out v)&&v!=null?Convert.ToString(v):"";}
 internal static string Hash(byte[] b){using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(b)).Replace("-","").ToLowerInvariant();}
 internal static string FileHash(string p){using(var h=SHA256.Create())using(var f=File.OpenRead(p))return BitConverter.ToString(h.ComputeHash(f)).Replace("-","").ToLowerInvariant();}
 internal static string Id(string url){Uri u;if(!Uri.TryCreate(url,UriKind.Absolute,out u)||u.Scheme!="https"||(u.Host!="www.douyin.com"&&u.Host!="douyin.com")||!System.Text.RegularExpressions.Regex.IsMatch(u.AbsolutePath,@"^/user/[A-Za-z0-9_-]{3,200}/?$"))return "";return u.AbsolutePath.TrimEnd('/').Split('/').Last();}
 internal QueueStore(string appRoot){root=appRoot;Directory.CreateDirectory(DirectoryRoot);bool existed=false;int invalid=0;var valid=new List<QueueSnapshot>();
  foreach(string name in new[]{"queue-a.json","queue-b.json"}){string path=Path.Combine(DirectoryRoot,name);if(!File.Exists(path))continue;existed=true;try{if(new FileInfo(path).Length>64L*1024*1024)throw new IOException("任务存档过大");var envelope=Json().Deserialize<Dictionary<string,object>>(File.ReadAllText(path,Encoding.UTF8));string body=S(envelope,"body");if(Hash(Encoding.UTF8.GetBytes(body))!=S(envelope,"sha256")){invalid++;continue;}var snapshot=Json().Deserialize<QueueSnapshot>(body);if(snapshot.tasks==null||snapshot.seen==null||snapshot.tasks.Count>1100||snapshot.seen.Count>20000){invalid++;continue;}valid.Add(snapshot);}catch{invalid++;}}
  data=valid.OrderByDescending(x=>x.generation).FirstOrDefault()??new QueueSnapshot{stream=Guid.NewGuid().ToString("N")};
  if(existed&&valid.Count==0){persistenceError="任务存档无法校验；已停止监听，请保留存档排查";data.enabled=false;}
  else if(invalid>0){data.enabled=false;Notice("一个任务快照损坏，已恢复可校验存档并暂停监听；可能缺少最近的状态，请核对任务后手动开启");}
  foreach(var t in data.tasks){if(t.status=="resolving"){t.status="pending";t.lease="";}else if(t.status=="composing"){t.status="verified";t.lease="";}else if(t.status=="playing"){t.status="ready";t.playToken="";t.error="上次播放中断，可重新播放";}if(t.status=="ready"&&(!File.Exists(Video(t))||FileHash(Video(t))!=t.videoHash)){t.status="failed";t.error="成片缓存校验失败";t.profile=null;}}
  if(persistenceError=="")Save();
 }
 void Save(){if(persistenceError!="")throw new IOException(persistenceError);data.generation++;string body=Json().Serialize(data);byte[] bytes=new UTF8Encoding(false).GetBytes(Json().Serialize(new{body=body,sha256=Hash(Encoding.UTF8.GetBytes(body))}));
  string file=Path.Combine(DirectoryRoot,data.generation%2==0?"queue-a.json":"queue-b.json");try{using(var f=new FileStream(file,FileMode.Create,FileAccess.Write,FileShare.Read)){f.Write(bytes,0,bytes.Length);f.Flush(true);}}catch(Exception e){data.enabled=false;persistenceError="任务存档写入失败，已停止接收和制片："+e.Message;throw new IOException(persistenceError);}
 }
 void Notice(string s){if(s==lastNotice&&Now()-lastNoticeAt<30000)return;lastNotice=s;lastNoticeAt=Now();data.warnings++;data.notices.Add(DateTime.Now.ToString("HH:mm:ss ")+s);if(data.notices.Count>50)data.notices.RemoveAt(0);}
 void Expire(){foreach(var t in data.tasks.Where(t=>(t.status=="resolving"||t.status=="composing"&&!QueueComposer.Busy)&&t.deadline<Now()).ToArray()){t.status="failed";t.error="任务租约超时；未采用其他用户资料";t.lease="";t.profile=null;data.failures++;Save();}}
 void Prune(){var old=data.tasks.Where(t=>t.status=="completed"||t.status=="archived").OrderBy(t=>t.updated).ToArray();foreach(var t in old.Take(Math.Max(0,old.Length-200)))data.tasks.Remove(t);}
 GiftTask Get(Dictionary<string,object> d){var t=data.tasks.Find(x=>x.id==S(d,"taskId"));if(t==null)throw new IOException("任务不存在");return t;}
 GiftTask Leased(Dictionary<string,object> d,string phase){var t=Get(d);if(t.status!=phase||t.lease!=S(d,"lease")||t.deadline<Now())throw new IOException("过期或不匹配的任务绑定");return t;}
 int FreeSlot(){for(int n=0;n<Slots;n++)if(!data.tasks.Any(t=>t.slot==n&&new[]{"composing","ready","playing"}.Contains(t.status)))return n;return -1;}
 internal string SlotPath(int slot,string kind){if(slot<0||slot>=Slots||!new[]{"video","profile","deco","result"}.Contains(kind))throw new IOException("缓存槽无效");string dir=Path.Combine(DirectoryRoot,"slots","s"+slot);Directory.CreateDirectory(dir);return Path.Combine(dir,kind+(kind=="profile"||kind=="deco"?".png":".mp4"));}
 string Video(GiftTask t){return SlotPath(t.slot,"result");}
 internal object State(bool details){lock(gate){Expire();return new{ok=true,enabled=data.enabled,stream=data.stream,edgeConnected=Now()-edgePing<16000,edgeState=edgeState,rendererConnected=Now()-rendererPing<16000,persistenceError=persistenceError,capacity=FreeSlot()>=0,pendingLimit=MaxPending,readyLimit=Slots,statistics=new{received=data.total,completed=data.completed,failures=data.failures,warnings=data.warnings,overflow=data.overflow},notices=data.notices.ToArray(),tasks=data.tasks.Where(t=>t.status!="completed"&&t.status!="archived").Select(t=>new{t.id,t.eventKey,t.status,t.created,t.updated,t.attempts,t.error,t.expectedId,t.sourceUrl,t.identityMethod,t.corrected,t.templateName,t.slot,nickname=S(t.profile,"nickname"),avatarDataUrl=details?S(t.profile,"avatarDataUrl"):"",gift=S(t.raw,"gift"),giftNickname=S(t.raw,"nickname"),count=S(t.raw,"count")}).ToArray()};}}
 internal object Config(Dictionary<string,object> d){lock(gate){if(persistenceError!="")throw new IOException(persistenceError);if(S(d,"action")=="new-stream"){if(data.enabled||listenerEnabled||Now()-edgePing>=16000||edgeBacklog>0||data.tasks.Any(t=>t.status!="completed"&&t.status!="archived"))throw new IOException("请先关闭监听、处理所有任务，并等待 Edge 助手确认缓冲为空后再开始新场次");Notice("已结束上场：收礼 "+data.total+"，完成 "+data.completed+"，捕获警告 "+data.warnings);data.stream=Guid.NewGuid().ToString("N");data.seen.Clear();data.total=data.completed=data.failures=data.warnings=data.overflow=0;Save();return State(false);}object v;if(d.TryGetValue("enabled",out v)){if(v is bool&&(bool)v&&Now()-edgePing<16000&&!listenerCompatible)throw new IOException("请先加载 V8.1.1 网页助手并刷新直播平台，再开启监听");data.enabled=v is bool&&(bool)v;}Save();return State(false);}}
 internal object Heartbeat(Dictionary<string,object> d){lock(gate){Uri u;if(!Uri.TryCreate(S(d,"url"),UriKind.Absolute,out u)||u.Scheme!="https"||u.Host!="anchor.douyin.com")throw new IOException("仅接受直播服务平台页面");edgePing=Now();listenerCompatible=S(d,"captureProtocol")=="causal-v1";edgeState=listenerCompatible?S(d,"state"):"旧网页助手已连接；请加载 V8.1.1 助手并刷新直播平台";if(!listenerCompatible&&data.enabled){data.enabled=false;Notice("已暂停旧助手监听；V8.1.1 异步身份获取需要新版助手，并刷新平台页面");Save();}int.TryParse(S(d,"backlog"),out edgeBacklog);listenerEnabled=S(d,"listenerEnabled")=="True";if(S(d,"warning")!=""){Notice(S(d,"warning"));Save();}return new{ok=true,enabled=data.enabled,stream=data.stream,capacity=data.tasks.Count(t=>t.status!="completed"&&t.status!="archived")<MaxPending&&data.seen.Count<20000};}}
 internal object Ingest(Dictionary<string,object> d){lock(gate){if(!data.enabled)return new{ok=true,accepted=new string[0],paused=true};if(S(d,"stream")!=data.stream)throw new IOException("监听场次不匹配");var accepted=new List<string>();object value;if(!d.TryGetValue("events",out value))throw new IOException("没有礼物记录");var collection=value as System.Collections.IEnumerable;var entries=collection==null?null:collection.Cast<object>().ToArray();if(entries==null||entries.Length>50)throw new IOException("事件批次无效");
  foreach(object entry in entries){var e=entry as Dictionary<string,object>;string key=S(e,"eventKey");if(key.Length<8||key.Length>250)throw new IOException("送礼事件标识无效");if(data.seen.Contains(key)){accepted.Add(key);continue;}
   if(data.tasks.Count(t=>t.status!="completed"&&t.status!="archived")>=MaxPending||data.seen.Count>=20000){data.overflow++;Notice("队列或事件标识容量已满，未接收的记录仍由助手保留；无法承诺零漏单");break;}
   var raw=new Dictionary<string,object>();bool oversized=false;foreach(string field in new[]{"nickname","profileUrl","recordId","text","gift","count","fingerprint","nodeToken","pageId","capturedSourceUrl","captureBasis","captureError"}){string text=S(e,field);int limit=field=="fingerprint"||field=="text"?4096:field=="profileUrl"||field=="capturedSourceUrl"?1024:field=="captureError"?500:256;if(text.Length>limit){oversized=true;text=text.Substring(0,limit);}raw[field]=text;}string url=S(e,"profileUrl"),basis="direct-href";if(Id(url)==""&&S(e,"captureBasis")=="causal-open"&&S(e,"nodeToken").Length==36&&S(e,"fingerprint")!=""){url=S(e,"capturedSourceUrl");basis="causal-open";}string identity=Id(url);var task=new GiftTask{id=Guid.NewGuid().ToString("N"),eventKey=key,stream=data.stream,status="pending",raw=raw,profile=null,created=Now(),updated=Now(),expectedId=identity,sourceUrl=identity==""?"":"https://www.douyin.com/user/"+identity,error="",identityMethod=identity==""?"":basis};if(S(e,"captureError")!=""){task.status="failed";task.error=S(raw,"captureError");data.failures++;}else if(oversized){task.status="failed";task.error="原始礼物行资料超过安全长度，未猜测或截短身份后制片；请核对身份";data.failures++;}data.tasks.Add(task);data.seen.Add(key);data.total++;accepted.Add(key);
  }Prune();Save();return new{ok=true,accepted=accepted.ToArray()};}}
 internal object ClaimIdentity(){lock(gate){Expire();if(!data.enabled||FreeSlot()<0||data.tasks.Any(x=>x.status=="resolving"||x.status=="verified"||x.status=="composing"))return new{ok=true,task=(object)null};var t=data.tasks.FirstOrDefault(x=>x.status=="pending");if(t==null)return new{ok=true,task=(object)null};t.status="resolving";t.lease=Guid.NewGuid().ToString("N");t.deadline=Now()+60000;t.attempts++;t.updated=Now();Save();return new{ok=true,task=new{t.id,t.lease,t.raw,t.expectedId,t.sourceUrl,t.identityMethod,t.deadline}};}}
 internal object BindTarget(Dictionary<string,object> d){lock(gate){var t=Leased(d,"resolving");string uid=Id(S(d,"sourceUrl"));if(uid=="")throw new IOException("没有可验证的账号标识");if(t.expectedId!=""&&uid!=t.expectedId){FailTask(t,"原始送礼目标与打开的主页账号不匹配");throw new IOException(t.error);}if(t.expectedId==""){if(S(d,"basis")!="causal-open"||S(d,"nodeToken")!=S(t.raw,"nodeToken")||S(d,"fingerprint")!=S(t.raw,"fingerprint"))throw new IOException("缺少与原始礼物记录绑定的点击证据");t.identityMethod="causal-open";}t.expectedId=uid;t.sourceUrl="https://www.douyin.com/user/"+uid;Save();return new{ok=true,expectedId=uid};}}
 internal object Profile(Dictionary<string,object> d){GiftTask t;Dictionary<string,object> p;string lease;
  lock(gate){t=Leased(d,"resolving");lease=t.lease;object value;if(!d.TryGetValue("profile",out value)||(p=value as Dictionary<string,object>)==null)throw new IOException("用户资料不完整");if(t.expectedId==""||Id(S(p,"sourceUrl"))!=t.expectedId||S(p,"identityId")!=t.expectedId||S(p,"canonicalId")!=t.expectedId){FailTask(t,"主页唯一账号标识不匹配，停止制片");throw new IOException(t.error);}if(S(p,"nickname").Trim()==""||S(p,"nickname").Length>256)throw new IOException("未读取完整昵称");if(!t.corrected&&S(t.raw,"nickname")!=""&&System.Text.RegularExpressions.Regex.Replace(S(t.raw,"nickname"),@"\s+"," ").Trim()!=System.Text.RegularExpressions.Regex.Replace(S(p,"nickname"),@"\s+"," ").Trim()){FailTask(t,"主页昵称与原送礼记录不一致，可能仍有旧资料或用户改名；请人工核对账号后重试");throw new IOException(t.error);}}
  string avatar=DownloadAvatar(S(p,"avatarUrl"));
  lock(gate){if(t.status!="resolving"||t.lease!=lease||t.deadline<Now())throw new IOException("头像下载完成时任务绑定已失效");t.profile=new Dictionary<string,object>{{"nickname",S(p,"nickname").Trim()},{"sourceUrl",t.sourceUrl},{"identityId",t.expectedId},{"avatarUrl",S(p,"avatarUrl")},{"avatarDataUrl",avatar}};t.status="verified";t.lease="";t.updated=Now();Save();return new{ok=true};}
 }
 internal static string DownloadAvatar(string url){Uri u;string[] allowed={"douyinpic.com","byteimg.com","ibytedtos.com","bytecdn.cn","douyincdn.com","pstatp.com","bytegoofy.com","avatars.githubusercontent.com"};if(!Uri.TryCreate(url,UriKind.Absolute,out u)||u.Scheme!="https"||u.Port!=443||u.UserInfo!=""||!allowed.Any(h=>u.Host==h||u.Host.EndsWith("."+h,StringComparison.OrdinalIgnoreCase)))throw new IOException("头像不是受支持的公开图片地址；请报告异常，未采用旧头像");ServicePointManager.SecurityProtocol=SecurityProtocolType.Tls12;var req=(HttpWebRequest)WebRequest.Create(u);req.Timeout=12000;req.ReadWriteTimeout=12000;req.AllowAutoRedirect=false;req.UserAgent="BeautyWeapon/8.0";
  using(var response=(HttpWebResponse)req.GetResponse()){if((int)response.StatusCode!=200)throw new IOException("头像下载未成功");using(var input=response.GetResponseStream())using(var output=new MemoryStream()){byte[] b=new byte[32768];int n;while((n=input.Read(b,0,b.Length))>0){if(output.Length+n>1048576)throw new IOException("头像超过 1 MB");output.Write(b,0,n);}output.Position=0;using(var image=Image.FromStream(output)){if(image.Width<1||image.Height<1||image.Width>4096||image.Height>4096)throw new IOException("头像尺寸无效");using(var normalized=new Bitmap(image,Math.Min(256,image.Width),Math.Min(256,image.Height)))using(var bytes=new MemoryStream()){normalized.Save(bytes,System.Drawing.Imaging.ImageFormat.Png);return "data:image/png;base64,"+Convert.ToBase64String(bytes.ToArray());}}}}
 }
 void FailTask(GiftTask t,string error){t.status="failed";t.error=error.Substring(0,Math.Min(error.Length,500));t.lease="";t.profile=null;t.updated=Now();data.failures++;Save();}
 internal object Fail(Dictionary<string,object> d){lock(gate){var t=Get(d);if(t.lease!=S(d,"lease")||!(t.status=="resolving"||t.status=="composing"))return new{ok=true,ignored=true};FailTask(t,S(d,"error"));return new{ok=true};}}
 internal object Archive(Dictionary<string,object> d){lock(gate){var t=Get(d);if(t.status!="failed")throw new IOException("仅可归档已失败任务");t.status="archived";t.profile=null;t.updated=Now();Prune();Save();return new{ok=true};}}
 internal object Retry(Dictionary<string,object> d){lock(gate){var t=Get(d);if(t.status!="failed")throw new IOException("仅异常任务可重试");string corrected=S(d,"sourceUrl");if(corrected!=""){string uid=Id(corrected);if(uid=="")throw new IOException("请输入完整抖音用户主页地址");t.expectedId=uid;t.sourceUrl="https://www.douyin.com/user/"+uid;t.identityMethod="manual-correction";t.corrected=true;}
  object reset;if(d.TryGetValue("resetTemplate",out reset)&&reset is bool&&(bool)reset){t.templateId="";t.templateName="";}t.status="pending";t.profile=null;t.error="";t.lease="";t.updated=Now();Save();return new{ok=true};}}
 internal object ClaimRender(Dictionary<string,object> d){lock(gate){Expire();rendererPing=Now();string owner=S(d,"owner");if(owner.Length!=32)throw new IOException("制片器标识无效");if(persistenceError!=""||QueueComposer.Busy||data.tasks.Any(x=>x.status=="composing")||manualDeadline>Now()||FreeSlot()<0)return new{ok=true,task=(object)null};var t=data.tasks.FirstOrDefault(x=>x.status=="verified");if(t==null||QueueComposer.InFlight(root))return new{ok=true,task=(object)null};rendererOwner=owner;t.slot=FreeSlot();t.status="composing";t.lease=Guid.NewGuid().ToString("N");t.deadline=Now()+240000;t.updated=Now();Save();return new{ok=true,task=new{t.id,t.lease,t.profile,t.expectedId,t.templateId,t.templateName,t.slot,t.deadline}};}}
 internal object SetTemplate(Dictionary<string,object> d){lock(gate){var t=Leased(d,"composing");if(t.templateId!=""&&t.templateId!=null&&t.templateId!=S(d,"templateId"))throw new IOException("重试不能偷偷换模板");t.templateId=S(d,"templateId");t.templateName=S(d,"templateName");Save();return new{ok=true};}}
 internal void Upload(Dictionary<string,object> d,string kind,Stream input,long length){GiftTask t;string path;lock(gate){t=Leased(d,"composing");if(!new[]{"video","profile","deco"}.Contains(kind))throw new IOException("仅可写入任务素材");if(t.renderMeta!=null&&S(t.renderMeta,"lease")==t.lease)throw new IOException("合成已经开始，禁止改变素材");path=SlotPath(t.slot,kind);}long limit=kind=="video"?VideoLimit:8*1024*1024;if(length<=0||length>limit)throw new IOException("素材超出大小限制");using(var output=new FileStream(path,FileMode.Create,FileAccess.Write,FileShare.None)){byte[] b=new byte[131072];long count=0;int n;while((n=input.Read(b,0,b.Length))>0){count+=n;if(count>limit)throw new IOException("素材超过限制");output.Write(b,0,n);}if(count!=length)throw new IOException("素材被截断");output.Flush(true);}lock(gate)Leased(d,"composing");}
 internal object Compose(Dictionary<string,object> d){GiftTask t;lock(gate){t=Leased(d,"composing");if(t.renderMeta!=null&&S(t.renderMeta,"lease")==t.lease)throw new IOException("合成已启动");t.renderMeta=d;Save();}
  ThreadPool.QueueUserWorkItem(_=>{try{QueueComposer.Render(root,this,t,d);lock(gate){if(t.status!="composing"||t.lease!=S(d,"lease"))return;t.videoHash=FileHash(Video(t));t.status="ready";t.updated=Now();t.lease="";Save();}}catch(Exception e){lock(gate)if(t.status=="composing"&&t.lease==S(d,"lease")){try{FailTask(t,e.Message);}catch(IOException){/* Save already records the persistent-storage failure; do not crash the streaming app. */}}}});return new{ok=true};}
 void CheckManualCache(){string cache=Path.Combine(root,"components","cache");if(!Directory.Exists(cache))return;var dirs=new Queue<string>();dirs.Enqueue(cache);long size=0;int entries=0;while(dirs.Count>0){string dir=dirs.Dequeue();foreach(string file in Directory.EnumerateFileSystemEntries(dir)){var a=File.GetAttributes(file);if((a&FileAttributes.ReparsePoint)!=0)throw new IOException("手动合成缓存包含链接目录，已停止写入；请核对缓存目录");if(++entries>2000)throw new IOException("旧手动合成缓存记录已达上限，请先自行备份整理；自动队列使用固定缓存槽，不会删除用户文件");if((a&FileAttributes.Directory)!=0)dirs.Enqueue(file);else{size+=new FileInfo(file).Length;if(size>=2L*1024*1024*1024)throw new IOException("旧手动合成缓存已达 2 GB，已停止继续积累；请先自行备份整理，不会自动删除任何文件");}}}}
 internal object Manual(Dictionary<string,object> d){lock(gate){if(S(d,"action")=="release"){manualDeadline=0;return new{ok=true};}if(manualDeadline>Now()||QueueComposer.InFlight(root)||data.tasks.Any(x=>x.status=="composing"))throw new IOException("已有视频正在合成，请等待当前任务完成");CheckManualCache();manualDeadline=Now()+240000;return new{ok=true};}}
 internal object Play(Dictionary<string,object> d){lock(gate){if(data.tasks.Any(x=>x.status=="playing"))throw new IOException("已有任务正在播放");var t=S(d,"taskId")==""?data.tasks.FirstOrDefault(x=>x.status=="ready"):Get(d);if(t==null||t.status!="ready")throw new IOException("没有已就绪的任务");if(FileHash(Video(t))!=t.videoHash){FailTask(t,"成片校验失败");throw new IOException(t.error);}t.status="playing";t.playToken=Guid.NewGuid().ToString("N");t.updated=Now();Save();return new{ok=true,task=new{t.id,t.playToken,t.profile,t.templateName,t.videoHash}};}}
 internal object End(Dictionary<string,object> d){lock(gate){var t=Get(d);if(t.status!="playing"||t.playToken!=S(d,"playToken"))throw new IOException("播放任务绑定不一致");object complete;bool done=d.TryGetValue("completed",out complete)&&complete is bool&&(bool)complete;t.status=done?"completed":"ready";t.playToken="";t.updated=Now();if(done){data.completed++;t.profile=null;}Prune();Save();return new{ok=true};}}
 internal void SendVideo(HttpListenerContext c,string id){string file;lock(gate){var t=data.tasks.Find(x=>x.id==id);if(t==null||!(t.status=="ready"||t.status=="playing"))throw new IOException("视频不在待播队列");file=Video(t);}using(var f=File.OpenRead(file)){long start=0,end=f.Length-1;string range=c.Request.Headers["Range"];if(!String.IsNullOrEmpty(range)){var m=System.Text.RegularExpressions.Regex.Match(range,@"^bytes=(\d+)-(\d*)$");if(!m.Success)throw new IOException("Range 无效");start=long.Parse(m.Groups[1].Value);if(m.Groups[2].Value!="")end=Math.Min(end,long.Parse(m.Groups[2].Value));if(start>end)throw new IOException("Range 越界");c.Response.StatusCode=206;c.Response.Headers["Content-Range"]="bytes "+start+"-"+end+"/"+f.Length;}c.Response.ContentType="video/mp4";c.Response.Headers["Accept-Ranges"]="bytes";c.Response.ContentLength64=end-start+1;f.Position=start;byte[] b=new byte[131072];long left=end-start+1;while(left>0){int n=f.Read(b,0,(int)Math.Min(b.Length,left));if(n==0)break;c.Response.OutputStream.Write(b,0,n);left-=n;}c.Response.Close();}}
}
