(()=>{
 'use strict';
 if(window.BW_QUEUE_WORKER){
  window.bwQueueRender=async task=>{
   await window.bwStartupReady;
   state.profile=structuredClone(task.profile);state.profileTs=Date.now();state.manualName='';nicknameInput.value='';renderProfile();await avatarImg.decode();
   const pool=task.templateId?window.bwQueueTemplates.index().filter(x=>x.id===task.templateId):[...window.bwQueueTemplates.index()];let chosen=null;const failures=[];
   while(pool.length){let i=0;if(!task.templateId){const a=new Uint32Array(1),limit=4294967296-4294967296%pool.length;do{crypto.getRandomValues(a);}while(a[0]>=limit);i=a[0]%pool.length;}const item=pool.splice(i,1)[0],size=item.state?.stageSize;stage.style.width=size?.w>0&&size.w<4096?size.w+'px':'';stage.style.height=size?.h>0&&size.h<2160?size.h+'px':'';if(await window.bwQueueTemplates.load(item.id)){chosen=item;break;}failures.push(item.name+'：'+window.bwQueueTemplates.error());}
   if(!chosen)throw Error('没有可用的完整模板。'+failures.join('；'));
   renderProfile();await document.fonts.ready;await avatarImg.decode();const p=await window.bwComposeLayers.profile();if(!p||!state.profile?.avatarDataUrl||state.profile.identityId!==task.expectedId)throw Error('头像昵称图层身份绑定失效');
   const dr=state.decoSrc?sceneRect(decoLayer):null;
   return {templateId:chosen.id,templateName:chosen.name,meta:{identityId:task.expectedId,templateId:chosen.id,appearTime:Number($('#appearTime').value),entryEffect:$('#entryEffect').value,profile:{cx:p.cx,cy:p.cy,w:p.w,h:p.h},deco:dr?{cx:dr.x+dr.w/2,cy:dr.y+dr.h/2,w:Math.round(dr.w),h:Math.round(dr.h)}:null},video:state.videoBlob,profile:await window.bwComposeLayers.mark(p.blob),deco:dr?await window.bwComposeLayers.mark(state.decoBlob):null};
  };return;
 }
 const API='http://127.0.0.1:38560/api/queue/',owner=crypto.randomUUID().replaceAll('-','');let snapshot=null,pollBusy=false,renderBusy=false,playing=null,posterId='',posterGeneration=0,worker=null,workerHtml='',workerUses=0,workerTouched=0,playBusy=false;
 // Native output reads video pixels; cross-port queue video must use CORS mode.
 pv.crossOrigin='anonymous';
 const names={pending:'待识别',resolving:'验证中',verified:'已验证',composing:'合成中',ready:'待播放',playing:'播放中',failed:'异常待处理'};
 async function request(action,data){const result=await window.bw71.api('/api/queue/'+action,data);if(result.ok===false)throw Error(result.error||'任务服务异常');return result;}
 window.bwQueueApi=request;
 const style=document.createElement('style');style.textContent=`#playBtn.bw815-ready,#bw7LivePlay.bw815-ready{background:#19f06f!important;color:#03180b!important;border-color:#74ffae!important;box-shadow:0 0 12px #19f06f55!important}#bw815QueueSettings button{width:auto;margin:6px 6px 0 0;padding:7px 10px} .bw8-panel{padding:10px;border:1px solid #29525d;border-radius:12px;background:#0a2029;margin-bottom:8px;font-size:12px;line-height:1.6}.bw8-head{display:flex;gap:8px;align-items:center;justify-content:space-between}.bw8-head strong{font-size:14px}.bw8-panel label{display:flex;gap:6px;align-items:center}.bw8-panel input{width:auto}.bw8-info{color:#a9c9d1;white-space:pre-wrap;margin:7px 0}.bw8-list{max-height:200px;overflow:auto}.bw8-task{border-top:1px solid #254650;padding:7px 0}.bw8-task strong{color:#dffcf2}.bw8-task small{display:block;color:#a7c3cc;word-break:break-word}.bw8-task button{width:auto;padding:4px 8px;margin-right:6px;font-size:11px}.bw8-error{color:#ffd67a}.bw8-count{color:#80efc9;font-size:12px}.bw8-live-count{display:block;font-size:12px;color:#83edcb}.bw8-panel button{margin-top:5px}.bw7-live .bw7-foot{max-height:55px;overflow:auto}#bw8RetryDialog{background:#0b2029;color:#def2f4;border:1px solid #38606c;border-radius:12px;padding:18px;width:min(500px,90vw)}#bw8RetryDialog input{width:100%;box-sizing:border-box}#bw8RetryDialog small{display:block;margin:10px 0;line-height:1.6}`;document.head.append(style);
 const panel=document.createElement('section');panel.className='bw8-panel';panel.innerHTML='<div class="bw8-head"><strong>送礼监听与制片队列</strong><label><input id="bw8Enabled" type="checkbox">自动监听</label></div><div id="bw8Info" class="bw8-info">正在连接任务服务…</div><div id="bw8Stats" class="bw8-count"></div><div id="bw8List" class="bw8-list"></div><small id="bw8Notice" class="bw8-error"></small>';$('.right').prepend(panel);
 const queueSettings=document.createElement('details');queueSettings.id='bw815QueueSettings';queueSettings.innerHTML='<summary>场次、历史任务与诊断</summary><p class="bw71-note">每次启动自动开启干净的新场次。旧计数、警告与任务留在历史记录，未播视频可恢复。清空头像/昵称只影响手动操作；停止队列任务请用任务下方的“停止任务”。</p><button id="bw8NewStream" class="secondary">归档当前场次并清空面板</button><button id="bw815HistoryRefresh" class="secondary">查看历史任务</button><div id="bw815History" class="bw8-list"></div>';$('#bw71Dialog').append(queueSettings);
 const count=document.createElement('small');count.className='bw8-live-count';$('#bw7LiveStatus').after(count);$('.bw7-foot').textContent='队列模式：只需点击播放。异常任务在普通模式处理。请保持 Edge 礼物明细展开，并将 anchor.douyin.com 加入始终活动网站。';
 const correction=document.createElement('dialog');correction.id='bw8RetryDialog';correction.innerHTML='<strong>人工核对送礼身份</strong><small id="bw8CorrectionInfo"></small><label>从原始礼物记录核对后粘贴用户主页地址<input id="bw8CorrectionUrl" placeholder="https://www.douyin.com/user/…"></label><small>这会记录人工纠正标记，重新读取并验证主页；系统不会凭昵称猜账号。</small><button id="bw8CorrectionConfirm">确认身份并重试</button><button id="bw8CorrectionCancel" class="secondary">取消</button>';document.body.append(correction);$('#bw8CorrectionCancel').onclick=()=>correction.close();let correcting='';
 $('#bw8CorrectionConfirm').onclick=async()=>{try{await request('retry',{taskId:correcting,sourceUrl:$('#bw8CorrectionUrl').value.trim()});correction.close();await poll();}catch(e){toast(e.message);}};
 function tasks(status){return snapshot?.tasks.filter(t=>t.status===status)||[];}
 function head(){return playing||tasks('playing')[0]||tasks('ready')[0];}
 const manualLivePlay=$('#bw7LivePlay').onclick,oldDoPlay=doPlay;
 doPlay=async function(){if(window.bwQueueActivePlaying){toast('队列视频播放中，请等待结束');return;}if(tasks('ready').length)return playNext();return oldDoPlay();};
 $('#bw7LivePlay').onclick=()=>tasks('ready').length?playNext():manualLivePlay();
 $('#bw8NewStream').onclick=async()=>{try{await request('config',{action:'new-stream'});$('#clearProfile').click();restorePreview();await poll();toast('当前面板已清零；旧任务保留在设置的历史记录中');}catch(e){toast(e.message);}};
 $('#bw815HistoryRefresh').onclick=async()=>{try{const h=await request('history',{}),list=$('#bw815History');list.replaceChildren();for(const t of h.tasks){const row=document.createElement('div');row.className='bw8-task';const title=document.createElement('small');title.textContent=(t.nickname||t.giftNickname||'未识别')+' · '+(names[t.status]||'已归档')+' · '+t.id.slice(0,8)+(t.templateName?' · '+t.templateName:'');const b=document.createElement('button');b.textContent=t.status==='ready'?'恢复到待播队列':'恢复并重新读取';b.onclick=()=>request('restore',{taskId:t.id}).then(async()=>{await poll();$('#bw815HistoryRefresh').click();toast('任务已恢复到当前场次');}).catch(e=>toast(e.message));row.append(title,b);list.append(row);}if(!h.tasks.length)list.textContent='没有未完成的历史任务';}catch(e){toast(e.message);}};
 $('#bw8Enabled').onchange=async()=>{try{await request('config',{enabled:$('#bw8Enabled').checked});await poll();}catch(e){toast(e.message);}};
 window.bwQueueRefreshLive=function(){if(!snapshot)return;const t=head();$('#bw7Name').textContent=t?.nickname||'等待送礼任务';window.bw71Avatar($('#bw7Avatar'),t?.avatarDataUrl||playing?.profile?.avatarDataUrl||'');$('#bw7Identity').textContent=t?'任务 '+t.id.slice(0,8)+' · 账号已确认':'尚无可播放任务';$('#bw711Template').textContent=t?.templateName?'本次模板：'+t.templateName:'';count.textContent='待播 '+tasks('ready').length+' · 处理中 '+snapshot.tasks.filter(x=>['pending','resolving','verified','composing'].includes(x.status)).length+' · 异常 '+tasks('failed').length;
  const message=playing?'正在播放：'+playing.nickname:tasks('ready').length?'已就绪，请核对头像和昵称后播放':tasks('composing').length?'FFmpeg 正在合成视频…':tasks('resolving').length?'正在读取并验证送礼用户…':snapshot.enabled?(snapshot.edgeConnected?'正在监听礼物，请保持明细展开':'等待 Edge 直播平台连接'):'自动监听已关闭';$('#bw7LiveStatus').textContent=message;$('#bw7LiveStatus').className='bw7-live-status '+(!t?'warn':'');$('#bw7LivePlay').disabled=!tasks('ready').length||!!playing||tasks('playing').length>0||playBusy||!pv.paused;$('#bw7LivePlay').textContent=playing?'播放中…':'立即播放';refreshPlay();if(t)poster(t);else if(posterId!==':empty'){posterId=':empty';++posterGeneration;previewPlaceholder('合成完成后显示核对画面');}};
 function refreshPlay(){const queueReady=tasks('ready').length>0,manualReady=window.bw7?.state().ready,blocked=!!playing||tasks('playing').length>0||playBusy||!pv.paused||state.composing;for(const id of ['playBtn','bw7LivePlay'])$('#'+id).classList.toggle('bw815-ready',!blocked&&(queueReady||manualReady));if(queueReady)$('#playBtn').disabled=blocked;}
 function restorePreview(time=0){if(state.videoSrc){restoreOriginal(time);return;}pv.pause();pv.removeAttribute('src');pv.load();state.playingComposed=false;sceneCtx.clearRect(0,0,1920,1080);}
 function previewPlaceholder(text){const canvas=$('#bw7Poster'),ctx=canvas.getContext('2d');delete canvas.dataset.bwQueuePoster;ctx.fillStyle='#030c10';ctx.fillRect(0,0,640,360);ctx.fillStyle='#90b9c3';ctx.font='18px Microsoft YaHei';ctx.textAlign='center';ctx.fillText(text,320,180);}
 async function poster(t){if(posterId===t.id)return;posterId=t.id;previewPlaceholder('正在读取待播画面…');const generation=++posterGeneration,v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.preload='metadata';v.src=API+'video?taskId='+t.id;
  try{await new Promise((r,j)=>{const timer=setTimeout(()=>j(Error('超时')),12000);v.onloadedmetadata=()=>{clearTimeout(timer);r();};v.onerror=()=>{clearTimeout(timer);j(Error('视频预览失败'));};});await new Promise((r,j)=>{const timer=setTimeout(()=>j(Error('超时')),12000);v.onseeked=()=>{clearTimeout(timer);r();};v.currentTime=Math.max(.001,v.duration-.15);});if(generation===posterGeneration){$('#bw7Poster').getContext('2d').drawImage(v,0,0,640,360);$('#bw7Poster').dataset.bwQueuePoster=t.id;}}catch{posterId='';}finally{v.removeAttribute('src');v.load();}}
 async function playNext(id=''){if(playBusy||playing||tasks('playing').length||!pv.paused||state.composing)return;playBusy=true;let task,oldEnd=pv.onended,oldError=pv.onerror;
  try{const reply=await request('play',{taskId:id});task=reply.task;playing={...task,nickname:task.profile.nickname,avatarDataUrl:task.profile.avatarDataUrl};window.bwQueueActivePlaying=true;sessionStorage.setItem('bw8Playback',JSON.stringify({taskId:task.id,playToken:task.playToken,completed:false}));
   const manualTime=pv.currentTime||0;pv.pause();pv.src=API+'video?taskId='+task.id;state.playingComposed=true;state.nativeClockSeq++;pv.load();await waitMeta();pv.currentTime=0;if(!state.nativeOutputActive)await openNativeOutput();if(!state.nativeOutputActive)throw Error('直播输出窗口未打开');
   const finish=async completed=>{if(!playing||playing.id!==task.id)return;pv.onended=oldEnd;pv.onerror=oldError;pv.pause();const ending={taskId:task.id,playToken:task.playToken,completed};sessionStorage.setItem('bw8Playback',JSON.stringify(ending));try{await request('end',ending);sessionStorage.removeItem('bw8Playback');}catch(e){toast('播放状态保存失败：'+e.message);}playing=null;window.bwQueueActivePlaying=false;restorePreview(manualTime);posterId='';await poll();};pv.onended=()=>finish(true);pv.onerror=()=>finish(false);await pv.play();sendNativeControl();startNativeFramePump();await poll();
  }catch(e){pv.onended=oldEnd;pv.onerror=oldError;if(task)await request('end',{taskId:task.id,playToken:task.playToken,completed:false}).then(()=>sessionStorage.removeItem('bw8Playback')).catch(()=>{});playing=null;window.bwQueueActivePlaying=false;restorePreview();toast('未开始播放：'+e.message);}finally{playBusy=false;window.bwQueueRefreshLive();}
 }
 function draw(){window.bwQueueOwnsLive=!!snapshot&&(snapshot.enabled||snapshot.tasks.some(t=>t.status!=='failed'));window.bwQueueWorking=renderBusy||tasks('composing').length>0||tasks('resolving').length>0;$('#bw8Enabled').checked=snapshot.enabled;$('#bw8Info').textContent=(snapshot.edgeConnected?snapshot.edgeState:'Edge 礼物页面未连接')+'\n身份：'+(tasks('resolving').length?'验证中':'等待任务')+' · 合成：'+(tasks('composing').length?'处理中':!templateIndex().length?'请先保存至少一个完整模板':'空闲')+(snapshot.capacity?'':'\n待播缓存已满，播放后继续制片');const s=snapshot.statistics;$('#bw8Stats').textContent='已收 '+s.received+' · 待播 '+tasks('ready').length+' · 完成 '+s.completed+' · 异常 '+tasks('failed').length+' · 捕获警告 '+s.warnings;$('#bw8Notice').textContent=snapshot.persistenceError||snapshot.notices.at(-1)||'';refreshPlay();
  const list=$('#bw8List');list.replaceChildren();for(const t of snapshot.tasks.slice(0,100)){const row=document.createElement('div');row.className='bw8-task';const title=document.createElement('strong');title.textContent=(t.nickname||t.giftNickname||'未识别用户')+' · '+names[t.status];const info=document.createElement('small');info.textContent=t.id.slice(0,8)+' · '+(t.gift||'礼物')+(t.corrected?' · 人工纠正':'')+(t.templateName?' · '+t.templateName:'');row.append(title,info);if(t.error){const e=document.createElement('small');e.className='bw8-error';e.textContent=t.error;row.append(e);}if(t.status==='composing'){const progress=document.createElement('small'),p=t.renderProgress||{};progress.textContent=(p.stage||'准备素材')+(p.duration&&p.frame>=0?' · '+Math.min(100,Math.floor(p.frame/(p.duration*60)*100))+'%':'')+(p.elapsedSeconds?' · '+p.elapsedSeconds+'秒':'');row.append(progress);}if(['pending','resolving','verified','composing'].includes(t.status)){const stop=document.createElement('button');stop.textContent='停止任务';stop.onclick=()=>request('cancel-task',{taskId:t.id}).then(poll).catch(e=>toast(e.message));row.append(stop);}if(t.status==='failed'){for(const correct of [false,true]){const b=document.createElement('button');b.textContent=correct?'核对身份':'重试';b.onclick=async()=>{if(correct){correcting=t.id;$('#bw8CorrectionInfo').textContent='原记录：'+t.giftNickname+' · '+t.gift+'\n'+t.error;$('#bw8CorrectionUrl').value=t.sourceUrl||'';correction.showModal();}else try{await request('retry',{taskId:t.id});poll();}catch(e){toast(e.message);}};row.append(b);}}if(t.status==='failed'){const again=document.createElement('button');again.textContent='重新选模板';again.onclick=()=>request('retry',{taskId:t.id,resetTemplate:true}).then(poll).catch(e=>toast(e.message));const archive=document.createElement('button');archive.textContent='归档异常';archive.onclick=()=>request('archive',{taskId:t.id}).then(poll).catch(e=>toast(e.message));row.append(again,archive);}list.append(row);}if(snapshot.tasks.length>100){const note=document.createElement('small');note.textContent='显示前 100 条，共 '+snapshot.tasks.length+' 条任务；先播放或处理前面的任务。';list.append(note);}if(window.bwQueueOwnsLive)window.bwQueueRefreshLive();}
 async function makeWorker(){if(worker?.isConnected&&worker.contentWindow?.bwQueueRender&&workerUses<6)return;worker?.remove();worker=null;workerUses=0;if(!workerHtml){workerHtml=await (await fetch('/')).text();const bootstrap="sync=function(){};poll=function(){};uiHeartbeat=function(){};pollGlobalCommand=function(){};saveWindowGeometry=function(){};loadHotkeys=function(){};renderSceneFrame=function(){};if(bc)bc.close();";workerHtml=workerHtml.replace('<script>','<script>window.BW_QUEUE_WORKER=true;').replace('startup();',bootstrap+'window.bwStartupReady=startup();');if(!workerHtml.includes('bwStartupReady'))throw Error('基线启动代码不匹配，未运行制片器');}
  workerHtml=workerHtml.replace('setInterval(poll,800);poll();','').replace('setInterval(uiHeartbeat,1200);uiHeartbeat();','').replace('setInterval(pollGlobalCommand,60);pollGlobalCommand();','').replace(/window\.addEventListener\('beforeunload',[^\n]+\);/g,'');
  worker=document.createElement('iframe');worker.setAttribute('aria-hidden','true');worker.style.cssText='position:fixed;left:-30000px;top:0;width:1920px;height:1080px;pointer-events:none;border:0';const ready=new Promise((r,j)=>{const timer=setTimeout(()=>j(Error('隔离制片器加载超时')),20000);worker.onload=()=>{if(!worker.contentWindow.bwQueueRender)return;clearTimeout(timer);r();};});worker.srcdoc=workerHtml;document.body.append(worker);await ready;if(!worker.contentWindow.bwQueueRender)throw Error('隔离制片器未就绪');}
 async function produce(){if(renderBusy||state.composing||!templateIndex().length)return;renderBusy=true;let task;
  try{const reply=await request('render-claim',{owner});task=reply.task;if(!task)return;workerTouched=Date.now();await makeWorker();let prepareTimer;const output=await Promise.race([worker.contentWindow.bwQueueRender(task),new Promise((r,j)=>prepareTimer=setTimeout(()=>j(Error('模板准备超过45秒；请检查素材完整性')),45000))]).finally(()=>clearTimeout(prepareTimer));await request('template',{taskId:task.id,lease:task.lease,templateId:output.templateId,templateName:output.templateName});
   for(const kind of ['video','profile','deco']){if(!output[kind])continue;await window.bw71.upload(API+'upload/'+kind,output[kind],{'X-BW-Task':task.id,'X-BW-Lease':task.lease});}
   await request('compose',{taskId:task.id,lease:task.lease,...output.meta});workerUses++;
  }catch(e){worker?.remove();worker=null;if(task)await request('render-fail',{taskId:task.id,lease:task.lease,error:e.message}).catch(()=>{});else $('#bw8Notice').textContent=e.message;}
  finally{renderBusy=false;}
 }
 const logButtons=document.createElement('div');logButtons.style.cssText='display:flex;gap:6px;flex-wrap:wrap;margin-top:6px';
 for(const [text,action] of [['导出旧失败日志','export-failure-logs'],['打开日志文件夹','failure-log-folder']]){const b=document.createElement('button');b.textContent=text;b.onclick=()=>request(action,{}).then(r=>{if(action==='export-failure-logs')toast('已保存 '+r.count+' 份旧任务日志到桌面；旧记录没有页面诊断。');}).catch(e=>toast(e.message));logButtons.append(b);}
 const logState=document.createElement('small');logState.style.cssText='display:block;overflow-wrap:anywhere';logButtons.append(logState);queueSettings.append(logButtons);
 async function poll(){if(worker&&!renderBusy&&Date.now()-workerTouched>120000){worker.remove();worker=null;workerUses=0;}if(pollBusy)return;pollBusy=true;try{snapshot=await request('state?details=1');if(!playing){let interrupted;try{interrupted=JSON.parse(sessionStorage.getItem('bw8Playback')||'null');}catch{}if(interrupted){const t=snapshot.tasks.find(t=>t.id===interrupted.taskId);if(t?.status==='playing'){await request('end',interrupted);snapshot=await request('state?details=1');}sessionStorage.removeItem('bw8Playback');}}draw();logState.textContent=snapshot.failureLogs?.error?'桌面日志写入失败：'+snapshot.failureLogs.error:snapshot.failureLogs?.lastPath?'本次失败日志已保存到桌面“美丽武器_读取失败日志”':'失败时自动记录到桌面“美丽武器_读取失败日志”';produce();}catch(e){$('#bw8Info').textContent='任务服务异常：'+e.message;}finally{pollBusy=false;}}
 window.bw8={poll,playNext,state:()=>snapshot,produce};poll();setInterval(poll,800);
})();



